services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=local
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - hotel-network
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev

networks:
  hotel-network:
    driver: bridge

volumes:
  node_modules:
